

services:
  kong-service:
    image: kong:latest
    volumes:
      - "./kong/config:/usr/local/kong/declarative"
      - "./kong/plugins:/usr/local/share/lua/5.1/kong/plugins"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_LOG_LEVEL: "debug"
      KONG_PLUGINS: "custom-auth"
      KONG_LUA_PACKAGE_PATH: "/usr/local/share/lua/5.1/?.lua;;"
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:7990:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    depends_on:
      - authservice
    networks:
      - kong-net

  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345 # Root password for MySQL
      MYSQL_DATABASE: userservice,authservice
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kong-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - kong-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kong-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - kong-net

  userservice:
    image: userservice:latest
    container_name: userservice
    environment:
      MYSQL_HOST: mysql-server
      MYSQL_PORT: 3306
      MYSQL_DB: userservice
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    ports:
      - "4000:4000"
    depends_on:
      - mysql-server
      - kafka
      - authservice
    networks:
      - kong-net

  authservice:
    image: authservice:latest
    container_name: authservice
    environment:
      MYSQL_HOST: mysql-server
      MYSQL_PORT: 3306
      MYSQL_DB: authservice
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    ports:
      - "8080:8080"
    depends_on:
      - mysql-server
      - kafka
    networks:
      - kong-net

  expenseservice:
    image: expenseservice:latest
    container_name: expenseservice
    ports:
      - '9820:9820'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql-server
      MYSQL_PORT: 3306
      MYSQL_DB: expenseservice
    depends_on:
      - kafka
      - mysql-server
    networks:
      - kong-net

  llmservice:
    image: llmservice:latest
    container_name: llmservice
    ports:
      - '5000:5000'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      OPENAI_API_KEY: 2HmoXlBLDqXWn83L8bPbn2j9LJQpbDaz
      KAFKA_TOPIC: expenses
    depends_on:
      - kafka
      - mysql-server
      - expenseservice
      - userservice
    networks:
      - kong-net

volumes:
  kong_data:
    driver: local
  mysql_data:
    driver: local

networks:
  kong-net:
    driver: bridge