version: '3.9'

services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345 # Root password for MySQL
      MYSQL_DATABASE: userservice,authservice
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  userservice:
    image: userservice:latest
    container_name: userservice
    environment:
      MYSQL_HOST: mysql-server
      MYSQL_PORT: 3306
      MYSQL_DB: userservice
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    ports:
      - "4000:4000"
    depends_on:
      - mysql-server
      - kafka
      - authservice

  authservice:
    image: authserice:latest
    container_name: authservice
    environment:
      MYSQL_HOST: mysql-server
      MYSQL_PORT: 3306
      MYSQL_DB: authservice
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    ports:
      - "8080:8080"
    depends_on:
      - mysql-server
      - kafka

  expenseservice:
    image: expenseservice:latest
    container_name: expenseservice
    ports:
      - '9820:9820'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql-server
      MYSQL_PORT: 3306
      MYSQL_DB: expenseservice
    depends_on:
      - kafka
      - mysql-server

  llmservice:
    image: llmservice:latest
    container_name: llmservice
    ports:
      - '5000:5000'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      OPENAI_API_KEY: 2HmoXlBLDqXWn83L8bPbn2j9LJQpbDaz
      KAFKA_TOPIC: expenses
    depends_on:
      - kafka
      - mysql-server
      - expenseservice
      - userservice

volumes:
  mysql_data:
    driver: local
