_format_version: "2.1"

services:
  - name: authservice
    url: http://host.docker.internal:8080
    routes:
      - name: auth-route
        paths:
          - /auth/v1
        strip_path: false
        preserve_host: false


  - name: userservice
    url: http://host.docker.internal:4000
    routes:
      - name: user-route
        paths:
          - /user/v1
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_endpoint: http://host.docker.internal:8080/auth/v1/ping

  - name: expenseservice
    url: http://host.docker.internal:9820
    routes:
      - name: expense-route
        paths:
          - /expense/v1
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_endpoint: http://host.docker.internal:8080/auth/v1/ping

  - name: llmservice
    url: http://host.docker.internal:5000
    routes:
      - name: llm-route
        paths:
          - /llm/v1
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_endpoint: http://host.docker.internal:8080/auth/v1/ping